apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: heroes-cosmosdb-instance
  namespace: default
spec:
  clusterServiceClassExternalName: azure-cosmos-mongo-db
  parameters:
    location: eastus
    resourceGroup: heroes-cosmosdb